<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputpos</name>
   <tag></tag>
   <elementGuidId>5f220b68-c4e4-48f4-89a2-82f9a570c702</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0b8b5ee-9779-4a12-8ef5-caedfb913083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>(brandCreate.selected_expedition == null || brandCreate.selected_expedition.length == 0) &amp;&amp; brandCreate.shipping_actived</value>
      <webElementGuid>0b80f4d3-cdb8-4ebf-950e-1aedbaf8213f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0735700d-9494-48a8-8cf0-808d9610054e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pos</value>
      <webElementGuid>1e519639-c07f-4c44-b7b9-a192bd44a660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>expedition.checked</value>
      <webElementGuid>261b8e00-ebe8-48b3-bf2b-568d63c7eb7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>updateSelected()</value>
      <webElementGuid>e9af612b-6eec-4646-9165-7a78b5781a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-valid-required</value>
      <webElementGuid>218e2a61-e071-471b-83e6-e89b7c607d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pos&quot;)</value>
      <webElementGuid>d197986f-6509-49ac-b670-ea3faf368fdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pos']</value>
      <webElementGuid>e330beb8-e8af-4778-8cc3-668a3ec3bc12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='expedition-list']/div[2]/label/input</value>
      <webElementGuid>227331e6-5113-4eb8-9ff9-be67ba501c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>b3a8d97c-5f96-44ec-8dbc-4da4313b9add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'pos']</value>
      <webElementGuid>29b23b18-5834-4d1f-82a5-d087fe82c603</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
