<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_form-control ng-pristine ng-untouched_25e022</name>
   <tag></tag>
   <elementGuidId>53c1675c-f059-49c8-9440-5dbede174a30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control.ng-pristine.ng-untouched.ng-invalid.ng-invalid-required.ng-valid-minlength</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e606802f-49f9-4700-bbcf-532ac515bef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e9164914-5ea0-4470-9de7-3f7ca45273b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2e4a89d2-8f78-4298-9297-3ffb627cff73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-invalid ng-invalid-required ng-valid-minlength</value>
      <webElementGuid>c70c1dbe-61cc-4e2d-b202-7a9368741617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-minlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>3f6649ad-631b-49fb-8025-49095f48cf30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>brandCreate.name</value>
      <webElementGuid>c3a0b457-cded-424c-9859-6156265f6e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>9b0f12ed-81b4-43a9-b586-0a37db27b2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;angular_content&quot;)/ui-view[1]/div[@class=&quot;page-content&quot;]/div[@class=&quot;panel&quot;]/div[@class=&quot;panel-heading&quot;]/form[@class=&quot;form-horizontal ng-pristine ng-invalid ng-invalid-required ng-valid-minlength&quot;]/div[@class=&quot;form-group form-material&quot;]/div[@class=&quot;col-sm-9&quot;]/input[@class=&quot;form-control ng-pristine ng-untouched ng-invalid ng-invalid-required ng-valid-minlength&quot;]</value>
      <webElementGuid>cf408383-9776-4212-b381-f01d1da4f159</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[3]</value>
      <webElementGuid>d0ba825f-9ab1-4c4f-a2f5-cfa425a4ab29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='angular_content']/ui-view/div/div/div/form/div/div/input</value>
      <webElementGuid>e463bc81-9d09-47da-9bd4-2adf3e91e141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/form/div/div/input</value>
      <webElementGuid>e3f10b54-c2a8-46fd-81fa-8cac3d498d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>8dde87ce-924c-47bd-84d7-7b1e3cbcffd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
