<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputsicepat</name>
   <tag></tag>
   <elementGuidId>db176937-4367-4992-a556-ac4314289aba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sicepat</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sicepat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5fb9c24f-11b3-47e0-b3a7-ea902f32d471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>(brandCreate.selected_expedition == null || brandCreate.selected_expedition.length == 0) &amp;&amp; brandCreate.shipping_actived</value>
      <webElementGuid>a62751c3-553b-4636-bd92-95efe70d317c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9afd366a-6707-4c44-a335-a52069a6aabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sicepat</value>
      <webElementGuid>e7abb416-0099-483b-8841-e7289bd95a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>expedition.checked</value>
      <webElementGuid>e043ece6-be38-4939-b1c8-bd431437584b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>updateSelected()</value>
      <webElementGuid>ff6e64dc-f5f1-45a9-9295-522e9fa4136a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-valid-required</value>
      <webElementGuid>3f9e9911-8a69-4b60-ad14-e70de9cfcd8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sicepat&quot;)</value>
      <webElementGuid>b00fdc2b-67ec-41a5-a5ff-2e8e1ee05445</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sicepat']</value>
      <webElementGuid>079f64d9-c0b3-4a3b-9873-0d1907a01929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='expedition-list']/div[7]/label/input</value>
      <webElementGuid>213a4725-69d5-4090-b622-e75f373579e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/label/input</value>
      <webElementGuid>926d0b60-2d2e-4281-9d2b-dd7b3e8c3fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'sicepat']</value>
      <webElementGuid>ad8ab618-ec52-463b-88ba-0127f85d5c68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
