<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputjne</name>
   <tag></tag>
   <elementGuidId>7d4f87cd-ecd6-49bd-83a7-5b7735be7666</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jne</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jne']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>25088877-7c6f-4799-87a4-e4ab3130ec98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>(brandCreate.selected_expedition == null || brandCreate.selected_expedition.length == 0) &amp;&amp; brandCreate.shipping_actived</value>
      <webElementGuid>8e7d8946-bdfa-48cc-b79e-afd0e2457b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>31dd5c9e-1ec2-4eba-a49c-336159b7d531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jne</value>
      <webElementGuid>f4fac670-b39d-41c6-bbef-c0be7a9d97fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>expedition.checked</value>
      <webElementGuid>18eb9d74-2259-4ed9-be3a-21b338face6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>updateSelected()</value>
      <webElementGuid>ce1ecf1a-4592-4b65-b4cc-5ceb26da989d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>d8342e99-415f-42f7-9daf-1bd79d07c526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>0bdf54b0-1bd0-4212-a032-a4d8ed42a281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jne&quot;)</value>
      <webElementGuid>a92e5755-60df-4c2a-b06c-feed9b1c3850</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jne']</value>
      <webElementGuid>011b2482-12f8-4d9e-b426-fd7516446cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='expedition-list']/div/label/input</value>
      <webElementGuid>75d6110c-16af-400b-98ae-3e0acd3ba60e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/label/input</value>
      <webElementGuid>050fb291-cedd-4d8e-9b8e-fb7bcdee95e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'jne']</value>
      <webElementGuid>232d83fc-cdaf-4272-9b69-ef13657b042d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
