<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputtiki</name>
   <tag></tag>
   <elementGuidId>44583eea-247f-46df-9d4b-836ca069aa92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tiki</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tiki']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e3ff830-1d42-4310-ba9c-215db8c4759d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>(brandCreate.selected_expedition == null || brandCreate.selected_expedition.length == 0) &amp;&amp; brandCreate.shipping_actived</value>
      <webElementGuid>29579d77-527d-4f92-a813-46f779b91219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7caf1f20-a493-4d90-a6e1-14028947095c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tiki</value>
      <webElementGuid>d7855c74-6c63-4687-a8d4-6d0f57e16cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>expedition.checked</value>
      <webElementGuid>c0cdfd59-2f0c-455f-b7e2-f18ad2952c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>updateSelected()</value>
      <webElementGuid>14a84fec-5512-48f0-a3ac-897b7fc972c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-valid-required</value>
      <webElementGuid>bd097f96-16c6-4123-aac5-dd0d7ff08887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tiki&quot;)</value>
      <webElementGuid>cf8f1312-4654-4444-8abd-63552a365036</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tiki']</value>
      <webElementGuid>dbed9958-1071-4f48-b7fc-c5949acfc54f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='expedition-list']/div[3]/label/input</value>
      <webElementGuid>f2be3fe8-77b3-4e10-955d-5eda9da80cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/input</value>
      <webElementGuid>ed773411-9ad3-46f6-8bf9-b6a2ef8e3768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'tiki']</value>
      <webElementGuid>fc5e9d88-a4e0-47e0-9799-48e5af55d7da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
