<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_KotamadyaKabupatenBandungBandungBand_59ed3d</name>
   <tag></tag>
   <elementGuidId>b80394a6-7983-4058-a04b-d76698fde261</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bdaa13ee-3059-4a76-8fbd-c18c5b592666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>brandCreate.shipping_actived</value>
      <webElementGuid>772ce69c-47e7-46b5-a20a-912ec30137b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>cities == null</value>
      <webElementGuid>62156192-bc13-4b9b-9aee-3adc4b9c3d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>20bd206e-4a0c-40b8-a227-efc1fe32f702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>35de4060-8d1d-402f-bd36-4e544623901d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>getExpeditionList()</value>
      <webElementGuid>9b1721df-894e-488c-9303-a75e95fcfe29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>brandCreate.city</value>
      <webElementGuid>3c6cdbab-9c2c-4a66-85f4-e56c8955e405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>city.city_id as city.city_name for city in cities</value>
      <webElementGuid>7eac6c1d-60c4-4f81-9e04-bddb46db2c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>61e3b21e-776c-463d-a24d-0386071ef700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>** Kotamadya/KabupatenBandungBandungBandung BaratBanjarBekasiBekasiBogorBogorCiamisCianjurCimahiCirebonCirebonDepokGarutIndramayuKarawangKuninganMajalengkaPangandaranPurwakartaSubangSukabumiSukabumiSumedangTasikmalayaTasikmalaya</value>
      <webElementGuid>7cdbbec8-0d86-4ddd-be72-debbebc6ffd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;city&quot;)</value>
      <webElementGuid>f2eba7dd-1504-480f-99de-a74fa75b2501</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='city']</value>
      <webElementGuid>da167240-ed43-4990-933c-7d656f1605b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='angular_content']/ui-view/div/div/div/form/div[10]/div/select</value>
      <webElementGuid>4c9d9e92-1682-446f-860d-3416a815c770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/select</value>
      <webElementGuid>61261874-86a4-4296-a43a-56810cd1925f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'city' and (text() = '** Kotamadya/KabupatenBandungBandungBandung BaratBanjarBekasiBekasiBogorBogorCiamisCianjurCimahiCirebonCirebonDepokGarutIndramayuKarawangKuninganMajalengkaPangandaranPurwakartaSubangSukabumiSukabumiSumedangTasikmalayaTasikmalaya' or . = '** Kotamadya/KabupatenBandungBandungBandung BaratBanjarBekasiBekasiBogorBogorCiamisCianjurCimahiCirebonCirebonDepokGarutIndramayuKarawangKuninganMajalengkaPangandaranPurwakartaSubangSukabumiSukabumiSumedangTasikmalayaTasikmalaya')]</value>
      <webElementGuid>1c4f67b1-ce58-44b6-8267-6f3816bde2d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
