<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select an activity factor</name>
   <tag></tag>
   <elementGuidId>dca427dd-4804-4ba2-a4e3-38bd01ef3d91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-activity_level-92-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-activity_level-92-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7e65a1f4-ed73-4a92-a98b-3dd3697cbac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>7c296938-3551-4b08-a14b-673441ed19a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-activity_level-92-container</value>
      <webElementGuid>a281bf8b-5b06-48eb-824c-c90594945bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Select an activity factor:</value>
      <webElementGuid>c2769326-1833-4932-8460-2cb6670a1473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select an activity factor:</value>
      <webElementGuid>d1495ea4-1507-4805-88e2-6c2fe46abbfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-activity_level-92-container&quot;)</value>
      <webElementGuid>63ea5ccb-d54b-499c-a228-f4aeae0b96aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-activity_level-92-container']</value>
      <webElementGuid>eba7ffd8-f546-4b15-b467-65d4475291ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span/span/span/span</value>
      <webElementGuid>1d173486-10f1-4be6-861d-b3adf6b55ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-activity_level-92-container' and @title = 'Select an activity factor:' and (text() = 'Select an activity factor:' or . = 'Select an activity factor:')]</value>
      <webElementGuid>5d52746e-2123-4b9b-9039-a8dba38b6d3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
