<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Little or no Exercise desk job</name>
   <tag></tag>
   <elementGuidId>3791d4d1-e272-4f99-b8fb-77fb226cd8e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-activity_level-92-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-activity_level-92-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eb4f1abb-31c7-46c7-8bcb-df22852b6998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>ec8a40d4-ecbe-4b58-a15a-b8efb7efa14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-activity_level-92-container</value>
      <webElementGuid>315b000b-f779-4dd3-b2e2-261d1174aa0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Little or no Exercise/ desk job</value>
      <webElementGuid>0eb23235-a1ba-41c5-bf1f-188ec6c2cd48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Little or no Exercise/ desk job</value>
      <webElementGuid>f13af682-dea9-4261-a5b8-b2bb83cb4d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-activity_level-92-container&quot;)</value>
      <webElementGuid>9d002020-42db-4405-8822-6ea6f1f503ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-activity_level-92-container']</value>
      <webElementGuid>dac437f0-f39b-4d42-a0c4-3400bd2a18c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span/span/span/span</value>
      <webElementGuid>390618e2-6567-4fc5-8f50-bd16e4710d68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-activity_level-92-container' and @title = 'Little or no Exercise/ desk job' and (text() = 'Little or no Exercise/ desk job' or . = 'Little or no Exercise/ desk job')]</value>
      <webElementGuid>d8784818-0b5c-41cc-a6dc-8895b4146c95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
