<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sex</name>
   <tag></tag>
   <elementGuidId>3970c6d0-62b0-4422-8757-39015aef162d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-sex-36-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-sex-ja-container</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;select2-sex-ja-container&quot;)[count(. | //span[@class = 'select2-selection__rendered' and @id = 'select2-sex-ja-container' and @title = 'Sex' and (text() = 'Sex' or . = 'Sex')]) = count(//span[@class = 'select2-selection__rendered' and @id = 'select2-sex-ja-container' and @title = 'Sex' and (text() = 'Sex' or . = 'Sex')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e6dec90b-8e98-42ca-883d-43dc606a1b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>36677997-8237-4021-b825-6003443abd8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-sex-ja-container</value>
      <webElementGuid>278d6ea6-6413-410f-8d3f-8c5c21c02e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sex</value>
      <webElementGuid>2ede2a5c-949f-4c8f-a5d1-11d2fb346e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sex</value>
      <webElementGuid>d0e707e1-7f6e-4911-9947-14792cb56ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-sex-ja-container&quot;)</value>
      <webElementGuid>26d9c79b-252d-489a-8785-cb4aa71fabbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-sex-ja-container']</value>
      <webElementGuid>5a82190d-1fec-425d-8bac-e35b228068a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>147eb247-c5f3-4942-9742-882555d47df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-sex-ja-container' and @title = 'Sex' and (text() = 'Sex' or . = 'Sex')]</value>
      <webElementGuid>fe1af95a-ed5c-47a3-a048-cf2e6483315d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
