<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Female</name>
   <tag></tag>
   <elementGuidId>b243f043-6ec0-4ecc-8e3c-a37565a5ad03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-sex-ja-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-sex-ja-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4ff67712-08cb-4cef-b363-dd6cc8702c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>ac820e2e-b07e-483e-a109-94ac71e0bfe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-sex-ja-container</value>
      <webElementGuid>c58ddd18-dda8-456a-8997-2c138437233d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Female</value>
      <webElementGuid>03946a26-a24d-481c-b9d1-082b70314068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Female</value>
      <webElementGuid>635ad0ff-a11b-400d-b0a5-1dd3e631222b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-sex-ja-container&quot;)</value>
      <webElementGuid>c1240b3f-1709-4582-8438-6c0f9d532600</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-sex-ja-container']</value>
      <webElementGuid>de439b09-4d84-4138-b4e9-6100184f6e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>2c5df41a-5197-451f-9501-36282e21cb1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-sex-ja-container' and @title = 'Female' and (text() = 'Female' or . = 'Female')]</value>
      <webElementGuid>04ceac5f-d94c-4970-8e58-d2c545d31824</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
