<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add New Varian</name>
   <tag></tag>
   <elementGuidId>07b57896-869d-4deb-97e4-bd1e19503987</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.pull-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Add New Varian')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eec5b17d-bc3f-4dc4-bba7-bd6df4ba26d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>2d42c356-c298-4f29-9cb8-af41d1d0793c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pull-right</value>
      <webElementGuid>c15aad36-87ea-4758-9402-0c66518a4d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>53</value>
      <webElementGuid>d96c3527-0243-4f3e-be4c-6158bcedcf46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>addVarian()</value>
      <webElementGuid>8cd7bd54-a02e-41a3-bb35-a4e3a527c33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add New Varian</value>
      <webElementGuid>0136a1cd-d38d-4d89-a8c7-f819bcfad19e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache no-svg no-inlinesvg no-smil no-svgclippaths js-menubar&quot;]/body[@class=&quot;dashboard site-menubar-fold site-menubar-hide modal-open&quot;]/div[@class=&quot;modal fade modalTopMargin in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-content&quot;]/form[@class=&quot;ng-dirty ng-valid-parse ng-valid ng-valid-required&quot;]/div[@class=&quot;modal-body&quot;]/a[@class=&quot;pull-right&quot;]</value>
      <webElementGuid>c55242b7-dd77-4496-9c09-ff12aeb64874</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add New Varian')]</value>
      <webElementGuid>e9e34327-ccf9-47cc-af55-d839fea3b7d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>3ca95afc-a730-443a-ab75-9ce161bdb403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>790b75c2-3b5a-4a4e-bf06-b835deabf4e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Add New Varian' or . = 'Add New Varian')]</value>
      <webElementGuid>18026b52-a75d-44ed-aff3-7ab7f6893fa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
