<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit_1</name>
   <tag></tag>
   <elementGuidId>1623b08b-5c9f-47dd-a287-f8f91af098aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-info.waves-effect.waves-light.waves-effect.waves-light.form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f35fbed8-1d6e-463b-8d21-2b58b4da7def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info waves-effect waves-light waves-effect waves-light form-control</value>
      <webElementGuid>245e2150-f528-4854-b637-22e0c20a7e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>57f0169d-c95c-4dd8-ad17-a1a1bf171562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>proCreate.$invalid</value>
      <webElementGuid>7ef9d597-6da3-42bb-9efd-09d01687f25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>submitProduct(proCreate.$valid, proCreate, 0)</value>
      <webElementGuid>35059576-6cb2-405e-aff7-c7407e0ffe7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1b647627-b7d3-43b6-b251-f46fe2360d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Submit
                                    </value>
      <webElementGuid>76536fce-d40f-4527-b33b-7ebaf38aceb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create-master-product&quot;)/div[@class=&quot;col-md-2 form-group&quot;]/button[@class=&quot;btn btn-info waves-effect waves-light waves-effect waves-light form-control&quot;]</value>
      <webElementGuid>f9a5efd5-445b-403f-8c5f-898461fcd100</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>6ccdddbc-d8a0-4de9-b0f6-d14a02f8858d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-form[@id='create-master-product']/div[10]/button</value>
      <webElementGuid>6993af4c-0f75-4c86-80db-fc8f1e93fafb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/button</value>
      <webElementGuid>47e6b143-cbdd-474c-b171-e543330a8c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                                        Submit
                                    ' or . = '
                                        Submit
                                    ')]</value>
      <webElementGuid>d60cf158-1559-4fa2-a0a1-5942c3059d95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
