<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Data Baru  Re-stok</name>
   <tag></tag>
   <elementGuidId>9f179e43-7ec4-4653-946c-934984b44a9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-info.navbar-btn.waves-effect.waves-light.pull-left</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7c1418d9-488b-4ef9-a0e4-ed12f4af6e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>slideAdd(isCollapsed)</value>
      <webElementGuid>549f9701-73fc-497d-ae91-6cacd085e57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1407c3b2-4698-4cfc-9dc9-d20dc9bd2629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info navbar-btn waves-effect waves-light  pull-left</value>
      <webElementGuid>a92b8618-a986-4591-ba79-00105c5f2b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>hak_akses[permalink+'/product_insert']</value>
      <webElementGuid>628bc72d-650d-4e9f-87f7-91357b934e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                             Data Baru / Re-stok
                        </value>
      <webElementGuid>398201fc-cbf0-4642-97e0-6df6a3e6e50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_product&quot;)/div[@class=&quot;panel&quot;]/div[@class=&quot;panel-body&quot;]/nav[@class=&quot;navbar&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;navbar-header&quot;]/button[@class=&quot;btn btn-info navbar-btn waves-effect waves-light  pull-left&quot;]</value>
      <webElementGuid>fff34068-ea3c-413c-9fe1-bc93d4b476ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[2]</value>
      <webElementGuid>4b5945f2-4bd7-4971-80a2-36d3413abf46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_product']/div/div/nav/div/div/button</value>
      <webElementGuid>bf7c6ab9-af8e-430d-ab39-323b357f7ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div/button</value>
      <webElementGuid>13bf227d-280d-46e3-a6ee-e11e50f31a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                             Data Baru / Re-stok
                        ' or . = '
                             Data Baru / Re-stok
                        ')]</value>
      <webElementGuid>0ddb98ee-b053-4328-98f4-efd7b575a553</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
