<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputproName</name>
   <tag></tag>
   <elementGuidId>e8b4612d-3156-4cc7-a7d9-998d480746be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#proName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='proName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ae3a17a-cc8f-4853-96ed-c863123ded9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d2bffa03-e89c-4a61-bf80-b89d7ce33a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>a9b0dcbe-bed5-4c07-acf0-61fe4561c168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>proName</value>
      <webElementGuid>b7c8e5e5-af9b-4b43-b326-5c03e6f9b43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>proCreate.name</value>
      <webElementGuid>b8fa4216-064d-4d44-949a-b5b2e7c47af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>!typeahead</value>
      <webElementGuid>0da7c583-1064-483a-bdec-dbf6fda2562c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Product Name*</value>
      <webElementGuid>cb9fd326-1e52-4eca-8a8c-a11e4ee5b369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>0e12b134-f04d-4849-98e1-3fb916aeef67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c32e3d8a-f85b-4265-a9ac-84eaf2dc023b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeahead-focus-on-select</name>
      <type>Main</type>
      <value>typeSelect()</value>
      <webElementGuid>be298765-e96e-4c86-a125-649b56ac734d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeahead-min-length</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>16ed3971-7d3a-478d-b0f7-c0db4e684c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeahead-show-hint</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a7e75c1c-4306-4567-8290-37ab4cd63e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeahead-template-url</name>
      <type>Main</type>
      <value>https://sistemtoko.com/js/templates/product/product-typeahead-name.html</value>
      <webElementGuid>e4faf669-9725-4856-88d5-45d2e5244859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uib-typeahead</name>
      <type>Main</type>
      <value>product as product.name for product in product.getData() | filter:{name:$viewValue}</value>
      <webElementGuid>166921e1-a705-4b8b-9f0a-3d3aa18dc577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>cead9615-869a-49ea-8b91-1a75635418fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f5f02118-b9df-468f-9062-18179ccb8e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>typeahead-161-6384</value>
      <webElementGuid>10b08c4a-6d0e-4bf6-9405-23f5e29350a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;proName&quot;)</value>
      <webElementGuid>995fb950-383e-4b24-b37c-5bd6fa2a6e07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='proName']</value>
      <webElementGuid>e704a11d-f6d0-4113-8b42-bb1f564544db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-form[@id='create-master-product']/div[2]/input</value>
      <webElementGuid>a718a98c-1822-4b60-8cc4-1145ce2cbe77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-form/div[2]/input</value>
      <webElementGuid>74c121ab-cd3a-4e06-9ebd-f133dc0433de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'proName' and @placeholder = 'Product Name*' and @type = 'text']</value>
      <webElementGuid>b687c4dc-e0f9-41e0-96b2-e66df9cf526c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
