<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputproPrice</name>
   <tag></tag>
   <elementGuidId>e6ad6d53-7f2b-47fd-858a-92241fb0677a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#proPrice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='proPrice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08abafbb-9a72-4e45-ac0b-30927df28a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>caaf9b43-f554-4958-855d-6ef292d41608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-invalid ng-invalid-required ng-touched ng-dirty-add ng-valid-parse-add ng-valid-add ng-invalid-remove ng-valid-required-add ng-invalid-required-remove ng-animate ng-pristine-remove</value>
      <webElementGuid>249f4da3-0da9-4751-b60d-0019f0ab12e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>33</value>
      <webElementGuid>8d098e24-e495-46ad-bdba-241087ece383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>proPrice</value>
      <webElementGuid>3912d039-db20-4bb4-8c24-7e13efac7184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Buy Price *</value>
      <webElementGuid>20b40060-d840-42a2-9203-abf46000f11c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>field</value>
      <webElementGuid>f2c31626-0b01-40e3-ae12-a83e4d0e6f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-animate</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>3fc1bbcd-cf90-421c-be46-a9522191e048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;proPrice&quot;)</value>
      <webElementGuid>981a59a9-f01c-4573-ad81-cb3c1b0f5fb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='proPrice']</value>
      <webElementGuid>7d664b07-a1f3-4a18-bedc-e0c7187d3e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-form[@id='create-master-product']/div[4]/div/span[2]/input</value>
      <webElementGuid>986397f6-2a19-4f48-9650-c152fca0b3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>e0f9ea8f-f1a8-402b-b4b0-8c31d9655d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'proPrice' and @placeholder = 'Buy Price *']</value>
      <webElementGuid>ba8cd3c5-2a0d-4179-a47f-49cb46d896cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
