<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputdata-varian-1</name>
   <tag></tag>
   <elementGuidId>5b8ba539-8073-4e30-9ff7-f20f8218bfdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#data-varian-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='data-varian-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9f6bba6-2d18-4e64-be33-db5f87157b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>69f63c69-c957-4782-8fe8-68eeb9ab3252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>data-varian-1</value>
      <webElementGuid>2dcbe67e-1970-4891-a030-f479b33d6c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>varianCreate.value[$index]</value>
      <webElementGuid>9813b2d6-9358-471d-9b3e-393e89f042bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>value, example: XL</value>
      <webElementGuid>19d4c8ed-53f7-4826-8fa8-e6e16eb7b950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-invalid ng-invalid-required ng-dirty-add ng-valid-parse-add ng-valid-add ng-invalid-remove ng-valid-required-add ng-invalid-required-remove</value>
      <webElementGuid>c0651f2e-937e-4356-91fc-85c8ac987323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>51</value>
      <webElementGuid>2692f4ce-22ff-4510-b8fa-42fc9cdaff84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-animate</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e8ddd84c-c1c8-4a8a-8a44-350281e7f5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data-varian-1&quot;)</value>
      <webElementGuid>443bf87a-20c1-439f-9dba-6f38a518819d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='data-varian-1']</value>
      <webElementGuid>4696f67c-abb7-4c8f-b1d2-f78b11503506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>8c10fefe-cba1-43b7-845f-8533ca571014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'data-varian-1' and @placeholder = 'value, example: XL']</value>
      <webElementGuid>4793e624-1d77-4cdb-9f56-3f4dc0100adc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
