<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputdata-varian-2</name>
   <tag></tag>
   <elementGuidId>5c2977a6-4c46-42f4-9908-0e3cb38973b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#data-varian-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='data-varian-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd009474-0d0d-4de9-93ad-2339c181574b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>63720997-aa83-4b24-b4d0-2a988117651a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>data-varian-2</value>
      <webElementGuid>ec8c15d7-820e-44e1-b048-311c1046e5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>varianCreate.value[$index]</value>
      <webElementGuid>c48fec40-b119-41bc-9007-ea2edbdba42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>value, example: XL</value>
      <webElementGuid>040dfb69-4dec-45ec-aa69-464ae648efee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-invalid ng-invalid-required ng-dirty-add ng-valid-parse-add ng-valid-add ng-invalid-remove ng-valid-required-add ng-invalid-required-remove</value>
      <webElementGuid>a46d3c1b-b081-4189-8447-48f763bbbd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>52</value>
      <webElementGuid>abe2e5fb-d32e-43d5-8d02-1dd19b86f954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-animate</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>6cf59511-aa21-4ade-a6a9-8e42ec541989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data-varian-2&quot;)</value>
      <webElementGuid>bd7ef0dd-da88-4527-8487-887c8f40c853</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='data-varian-2']</value>
      <webElementGuid>33ad0e38-698e-45b7-b2a0-f6107765310a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>ef1e0c87-2039-44f8-b749-7dfaaf686daf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'data-varian-2' and @placeholder = 'value, example: XL']</value>
      <webElementGuid>ca735bef-5290-438a-9c1f-68e1ea6b3eea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
