<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputproVarian</name>
   <tag></tag>
   <elementGuidId>7f5d978b-624b-495d-9679-bb492194c960</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#proVarian</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='proVarian']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>528a3e4b-11ec-442b-a398-2b75c70a09b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8d876929-88bf-4813-a2db-aeaed6beaaa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>proVarian</value>
      <webElementGuid>da894007-333e-4995-aa63-aacdf44e839a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-focus</name>
      <type>Main</type>
      <value>openVarian()</value>
      <webElementGuid>d0506033-e092-410d-bcc2-89768600c5ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>!getVarian.length</value>
      <webElementGuid>2b895fa1-c765-425c-8b94-3a721a7af5fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Varian</value>
      <webElementGuid>c795d95e-a43a-4f97-bb09-cb722dddb035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>a4fc9971-77e4-4195-8edf-82c607e0bad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>668d82a4-8d7b-417d-ae13-cec19a1d725e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;proVarian&quot;)</value>
      <webElementGuid>7ffd74b9-9332-4556-ac77-2b46bc0518b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='proVarian']</value>
      <webElementGuid>4a8ec6ad-b1f9-4e7e-a1c9-3c44770061cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-form[@id='create-master-product']/div[3]/input</value>
      <webElementGuid>6e9cfdbe-91bf-4631-a0ae-34f6a5059d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-form/div[3]/input</value>
      <webElementGuid>fff64fa4-b244-4cc0-b259-f01ed52aeee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'proVarian' and @placeholder = 'Varian' and @type = 'text']</value>
      <webElementGuid>2c9566f7-2ad3-45e8-8499-17d6b3efbcf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
