<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputdata-varian-0</name>
   <tag></tag>
   <elementGuidId>8cecea5c-a259-4641-9807-d77174623f2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#data-varian-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='data-varian-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd9ae101-e60e-46fd-875c-6ea30f50ad1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84a8707a-e205-44da-8779-4fe1e443e0ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>data-varian-0</value>
      <webElementGuid>bd5cd92d-c931-4d39-b1f3-ef00957834cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>varianCreate.value[$index]</value>
      <webElementGuid>f8f6b79b-14e0-46ae-99be-f69d8b76da81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>value, example: XL</value>
      <webElementGuid>35e0faac-9635-492b-ad65-6e7233d62985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-invalid ng-invalid-required ng-dirty-add ng-valid-parse-add ng-valid-add ng-invalid-remove ng-valid-required-add ng-invalid-required-remove</value>
      <webElementGuid>c406b105-1431-4511-ae69-1c6f9bac3c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>3713e9f0-ea91-43a7-98fa-a57cfdde215e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-animate</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d1075831-2407-432d-b9e4-9182c5629567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data-varian-0&quot;)</value>
      <webElementGuid>44c9205b-02b3-44ec-8d90-c72a69696b21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='data-varian-0']</value>
      <webElementGuid>8907738d-c76e-4a20-ad82-84f531018d4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>24e9f80b-bfae-4820-841f-2f986848a971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'data-varian-0' and @placeholder = 'value, example: XL']</value>
      <webElementGuid>cfd6cc51-86f1-4e90-aff2-84727dcce1ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
