<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ssn</name>
   <tag></tag>
   <elementGuidId>a7b9b4d8-9daf-42d7-b8be-2e0844f97cf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ssn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ssn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5257abcc-5f56-45cd-9c35-6202ef014043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ssn</value>
      <webElementGuid>7c94ab5f-bbf0-47e1-999c-f82f3ed1323a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ssn</value>
      <webElementGuid>28c00ffe-8219-4474-81d9-42a93d930614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5039764-cbd6-4b1e-a684-3c11dbffbb6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0b6a71c5-1085-46f7-b274-5f91b67762f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ssn&quot;)</value>
      <webElementGuid>a1967bc3-e4e1-4a9f-ad14-381e02fb7255</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ssn']</value>
      <webElementGuid>f388fae1-b7fc-4acb-9819-e187df08089e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='lookupForm']/table/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>5b53b341-a3fc-4293-a2de-314069030603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input</value>
      <webElementGuid>44275543-0d3d-41e3-81a5-08e81f4d0746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ssn' and @name = 'ssn' and @type = 'text']</value>
      <webElementGuid>2cb5f0f1-3181-42a8-8c95-15c9ef50f2ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
