<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sex</name>
   <tag></tag>
   <elementGuidId>f4afdd39-d012-4b0a-9d43-2d25dc5ed391</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-sex-h2-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-sex-h2-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>82c790bd-7dfe-4c99-a437-9c95a36e1338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>9d86c6c8-9016-47a8-b190-cf8102a67eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-sex-h2-container</value>
      <webElementGuid>f8317cb7-d523-4392-8ebd-e0436b6620da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sex</value>
      <webElementGuid>9c4f057b-2278-49c8-a072-04ab6f8af4ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sex</value>
      <webElementGuid>23d7f0bb-1054-4724-9517-268a788b0216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-sex-h2-container&quot;)</value>
      <webElementGuid>d5caff1a-fd0b-4b43-9519-213c3e116da8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-sex-h2-container']</value>
      <webElementGuid>f6659a73-830e-4ee6-88aa-2487351e636a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>937d02f0-79e5-4ada-ae8a-3e87d4159b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-sex-h2-container' and @title = 'Sex' and (text() = 'Sex' or . = 'Sex')]</value>
      <webElementGuid>40a225b3-6ff6-413a-851e-298edeec2dfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
