<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_navbar-brand-logo</name>
   <tag></tag>
   <elementGuidId>cc43dab5-13e7-4563-a20b-8682aaa20bba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.navbar-brand-logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://sistemtoko.com/img/logo.png')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>20694f63-cf9b-4302-ad8a-e4e99cf5d300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar-brand-logo</value>
      <webElementGuid>95f1cf2a-73d5-4d26-8757-e6a4a2469a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>https://sistemtoko.com/img/logo.png</value>
      <webElementGuid>6dc34b02-60c8-45ae-9dc7-168e81ece5ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://sistemtoko.com/img/logo.png</value>
      <webElementGuid>76c4aaa4-8e53-414b-bc97-f36a926f8957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache no-svg no-inlinesvg no-smil no-svgclippaths js-menubar&quot;]/body[@class=&quot;dashboard site-menubar-fold site-menubar-hide&quot;]/nav[@class=&quot;site-navbar navbar navbar-default navbar-fixed-top navbar-mega navbar-inverse bg-blue-600&quot;]/div[@class=&quot;navbar-header&quot;]/div[@class=&quot;navbar-brand navbar-brand-center&quot;]/img[@class=&quot;navbar-brand-logo&quot;]</value>
      <webElementGuid>ba8b76a5-e485-4f11-b69a-317351595d43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://sistemtoko.com/img/logo.png')]</value>
      <webElementGuid>800b3833-fff8-4ef2-9b23-f1ea69acc8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>0ee7521b-992b-4cb4-b964-aa95e66ad44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://sistemtoko.com/img/logo.png']</value>
      <webElementGuid>16f2d8ed-5aff-4bbf-b956-6550027ffb0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
