<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Welcome Lintani Afina Hajar Raudhoti</name>
   <tag></tag>
   <elementGuidId>f8594fbd-9493-4c42-be7c-c3314a70e732</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='leftPanel']/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.smallText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>45e1efae-6503-4551-ae5d-da820b2d3d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>smallText</value>
      <webElementGuid>1aaa7a8c-df8c-4735-9abc-f215f371286c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome Lintani Afina Hajar Raudhoti</value>
      <webElementGuid>5ad44332-9c26-4361-bf07-13d1e8151f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftPanel&quot;)/p[@class=&quot;smallText&quot;]</value>
      <webElementGuid>015d22f2-7588-484f-a747-b31a42f11b9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftPanel']/p</value>
      <webElementGuid>70929ef6-9cae-4923-90b0-adacac3610d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/p</value>
      <webElementGuid>526dd2a9-549b-4b53-8690-6b914c2e152e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Welcome Lintani Afina Hajar Raudhoti' or . = 'Welcome Lintani Afina Hajar Raudhoti')]</value>
      <webElementGuid>4a63d5dd-f608-4a73-b3d7-b7cb4c0a4564</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
