<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit Varian</name>
   <tag></tag>
   <elementGuidId>5b481836-6a8f-4129-9da7-67b41af85e44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.dropdown-menu.dropdown-menu-right > li:nth-of-type(4) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list_product']/div/div/table/tbody/tr/td[11]/div/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d62607f9-8b40-4c2e-9f2d-653c10f018b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>6e3e1592-4ab6-4070-8190-31415257ba72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>editVarian(data)</value>
      <webElementGuid>0a5b4d91-737e-47c6-b411-bb8dfcdd02d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>hak_akses[permalink+'/product_edit']</value>
      <webElementGuid>7a292abe-07cb-49bb-8c2c-a08efcef711a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Edit Varian</value>
      <webElementGuid>12671520-c81d-429c-88c2-1315ec54c22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_product&quot;)/div[@class=&quot;panel&quot;]/div[@class=&quot;panel-body&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[1]/td[@class=&quot;action_brand&quot;]/div[@class=&quot;btn-group open&quot;]/ul[@class=&quot;dropdown-menu dropdown-menu-right&quot;]/li[4]/a[1]</value>
      <webElementGuid>d8526ab4-f1b1-46e0-82b4-d70d1c53c2e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_product']/div/div/table/tbody/tr/td[11]/div/ul/li[4]/a</value>
      <webElementGuid>a14642f8-f8ad-4b97-a948-912aba509521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit Varian')]</value>
      <webElementGuid>94fa0602-3631-4f82-ae5b-aab513acdff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[11]</value>
      <webElementGuid>25717775-d785-44d7-ad8c-4f29ca552ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/div/ul/li[4]/a</value>
      <webElementGuid>59c6a22c-1f74-4156-b09d-1c5e2091c656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = ' Edit Varian' or . = ' Edit Varian')]</value>
      <webElementGuid>fc49d206-157a-48ba-b7e0-b2b3edb2c3f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
