<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputproPrice</name>
   <tag></tag>
   <elementGuidId>fadbb2d4-01ab-4a62-a6f3-dee8b5137179</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#proPrice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='proPrice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e486fa60-32f1-40a6-99de-82dff7f3f83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ac3caec4-8fb7-4b3f-b2fd-6ecb64af63ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-valid-required</value>
      <webElementGuid>413c714c-f3ea-4407-b118-b25a4cbc59d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>33</value>
      <webElementGuid>0e8491a8-3ac2-4bca-9e99-75eb012f17fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>proPrice</value>
      <webElementGuid>00958754-c3d2-4baa-944e-7b174bb4d5a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Buy Price *</value>
      <webElementGuid>02428bbc-6ab2-4fb2-8314-b4f558557b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>field</value>
      <webElementGuid>352b1685-5c72-432d-8860-2a06cfc9d689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache no-svg no-inlinesvg no-smil no-svgclippaths js-menubar&quot;]/body[@class=&quot;dashboard site-menubar-fold site-menubar-hide modal-open&quot;]/div[@class=&quot;modal fade modalTopMargin in&quot;]/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-content&quot;]/form[@class=&quot;form-horizontal ng-pristine ng-valid-max-tags ng-valid-min-tags ng-valid-leftover-text ng-valid ng-valid-required&quot;]/div[@class=&quot;modal-body row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;col-md-9&quot;]/div[@class=&quot;input-group&quot;]/span[2]/input[@id=&quot;proPrice&quot;]</value>
      <webElementGuid>d7c0d895-7057-4427-9568-a7b57c108642</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='proPrice']</value>
      <webElementGuid>434265da-d1c0-4306-952c-69e6365d23b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>a7744b14-6ab5-41ad-bc28-595396f7b7a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'proPrice' and @placeholder = 'Buy Price *']</value>
      <webElementGuid>72c31ff3-2a73-4858-b41c-08c5fb991131</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
